/* eslint-disable import/no-extraneous-dependencies */
/* eslint-disable import/no-named-as-default */
/* eslint-disable import/no-named-as-default-member */
/* eslint-disable react/prop-types */

'use client';

import './globals.css';
import React from 'react';
import { Inter } from 'next/font/google';
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';
// eslint-disable-next-line import/no-unresolved, import/extensions
import ChakraUiProvider from '../providers/chakra-ui.provider';
import Layout from '../components/Layout';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <ChakraUiProvider>
          <Layout>
            {children}
            <ProgressBar
              height="4px"
              color="#f0f0f0"
              options={{ showSpinner: false }}
              shallowRouting
            />
          </Layout>
        </ChakraUiProvider>
      </body>
    </html>
  );
}
