import './globals.css'
import { Inter } from 'next/font/google'
import ChakraUiProvider from '@/providers/chakra-ui.provider'
// import Head from 'next/head'
import Layout from '../components/Layout'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <ChakraUiProvider>
          <Layout>{children}</Layout>
        </ChakraUiProvider>
      </body>
    </html>
  )
}
