/* eslint-disable import/no-named-as-default */
/* eslint-disable import/no-named-as-default-member */
/* eslint-disable react/prop-types */
import './globals.css';
import React from 'react';
import { Inter } from 'next/font/google';
// eslint-disable-next-line import/no-unresolved, import/extensions
import ChakraUiProvider from '../providers/chakra-ui.provider';
// import Head from 'next/head'
import Layout from '../components/Layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <ChakraUiProvider>
          <Layout>{children}</Layout>
        </ChakraUiProvider>
      </body>
    </html>
  );
}
